### ISSUE TITLE
optionally open folder in new window

### ISSUE THREAD

**Issue by ebmshenfield** [t9md/atom-project-folder#3]
It would be nice if, using a specific keypattern, selecting a folder would open it in a new window.

**Comment by t9md** [comment]
Will implement it, thank you for suggestion.

**Comment by t9md** [comment]
I noticed your PR used `ctrl-n` as default keymap, but ctrl-n, p is broadly used as move-up/down cursor or items in select-list, so it conflict.
I picked ctrl-enter as default keymap. Will release once travis-CI test passed.
